INSERT INTO cities VALUES 
(1, 'Aceh'),
(2, 'Medan'),
(3, 'Palembang'),
(4, 'Bandung'),
(5, 'Jakarta Timur'),
(6, 'Jakarta Selatan'),
(7, 'Jakarta Barat'),
(8, 'Jakarta Utara'),
(9, 'Jakarta Pusat'),
(10, 'Surabaya'),
(11, 'Bali'),
(12, 'Yogyakarta'),
(13, 'Lombok'),
(14, 'Bogor'),
(15, 'Semarang'),
(16, 'Banten'),
(17, 'Lampung'),
(18, 'Bengkulu'),
(19, 'Jambi'),
(20, 'Riau'),
(21, 'Bengkulu'),
(22, 'Jambi'),
(23, 'Lampung'),
(24, 'Banten'),
(25, 'Bandung'),
(26, 'Sukabumi'),
(27, 'Cirebon'),
(28, 'Tasikmalaya'),
(29, 'Garut'),
(30, 'Ciamis'),
(31, 'Kuningan'),
(32, 'Cianjur'),
(33, 'Majalengka'),
(34, 'Sumedang'),
(35, 'Indramayu'),
(36, 'Subang'),
(37, 'Purwakarta'),
(38, 'Karawang'),
(39, 'Bekasi');

INSERT INTO houses VALUES 
('Aura House 2bds Eco Bamboo House, Pool, River View', 
3600000, 
'Aura house is a beautiful & unique eco bamboo house built on the west bank of the River Ayung facing east to catch sunrise. Aura House is situated 25min away from Ubud, and 35min away from Canggu.',
'Canggu',
1,
11 )


INSERT INTO houses_details VALUES
()