// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// CityUsecase is an autogenerated mock type for the CityUsecase type
type CityUsecase struct {
	mock.Mock
}

// GetCities provides a mock function with given fields:
func (_m *CityUsecase) GetCities() (*[]entity.City, error) {
	ret := _m.Called()

	var r0 *[]entity.City
	if rf, ok := ret.Get(0).(func() *[]entity.City); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.City)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCityUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCityUsecase creates a new instance of CityUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCityUsecase(t mockConstructorTestingTNewCityUsecase) *CityUsecase {
	mock := &CityUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
