// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// PickupStatusRepository is an autogenerated mock type for the PickupStatusRepository type
type PickupStatusRepository struct {
	mock.Mock
}

// GetPickupStatus provides a mock function with given fields:
func (_m *PickupStatusRepository) GetPickupStatus() ([]entity.PickupStatus, error) {
	ret := _m.Called()

	var r0 []entity.PickupStatus
	if rf, ok := ret.Get(0).(func() []entity.PickupStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PickupStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPickupStatusRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPickupStatusRepository creates a new instance of PickupStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPickupStatusRepository(t mockConstructorTestingTNewPickupStatusRepository) *PickupStatusRepository {
	mock := &PickupStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
