// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// PickupStatusUsecase is an autogenerated mock type for the PickupStatusUsecase type
type PickupStatusUsecase struct {
	mock.Mock
}

// GetPickupStatus provides a mock function with given fields:
func (_m *PickupStatusUsecase) GetPickupStatus() (*dto.PickupStatusLists, error) {
	ret := _m.Called()

	var r0 *dto.PickupStatusLists
	if rf, ok := ret.Get(0).(func() *dto.PickupStatusLists); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PickupStatusLists)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPickupStatusUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewPickupStatusUsecase creates a new instance of PickupStatusUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPickupStatusUsecase(t mockConstructorTestingTNewPickupStatusUsecase) *PickupStatusUsecase {
	mock := &PickupStatusUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
