// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// WalletTransactionUsecase is an autogenerated mock type for the WalletTransactionUsecase type
type WalletTransactionUsecase struct {
	mock.Mock
}

// GetWalletTransactions provides a mock function with given fields: s, sortBy, sort, limit, page
func (_m *WalletTransactionUsecase) GetWalletTransactions(s string, sortBy string, sort string, limit int, page int) (*[]entity.WalletTransaction, error) {
	ret := _m.Called(s, sortBy, sort, limit, page)

	var r0 *[]entity.WalletTransaction
	if rf, ok := ret.Get(0).(func(string, string, string, int, int) *[]entity.WalletTransaction); ok {
		r0 = rf(s, sortBy, sort, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.WalletTransaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, int, int) error); ok {
		r1 = rf(s, sortBy, sort, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletTransactionsUser provides a mock function with given fields: walletID
func (_m *WalletTransactionUsecase) GetWalletTransactionsUser(walletID int) (*[]entity.WalletTransaction, error) {
	ret := _m.Called(walletID)

	var r0 *[]entity.WalletTransaction
	if rf, ok := ret.Get(0).(func(int) *[]entity.WalletTransaction); ok {
		r0 = rf(walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.WalletTransaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: t
func (_m *WalletTransactionUsecase) TopUp(t dto.TopUpRequest) (*dto.TopUpResponse, error) {
	ret := _m.Called(t)

	var r0 *dto.TopUpResponse
	if rf, ok := ret.Get(0).(func(dto.TopUpRequest) *dto.TopUpResponse); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TopUpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.TopUpRequest) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWalletTransactionUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletTransactionUsecase creates a new instance of WalletTransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletTransactionUsecase(t mockConstructorTestingTNewWalletTransactionUsecase) *WalletTransactionUsecase {
	mock := &WalletTransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
